package org.talend.designer.codegen.translators.orchestration;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.core.model.process.IConnection;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import org.talend.core.model.process.EConnectionType;
import java.util.ArrayList;
import java.util.List;

public class TPartitionerEndJava
{
  protected static String nl;
  public static synchronized TPartitionerEndJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TPartitionerEndJava result = new TPartitionerEndJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "\tboolean forceShutdown_";
  protected final String TEXT_2 = " = false;" + NL + "\t" + NL + "    for (int i_";
  protected final String TEXT_3 = " = 0; i_";
  protected final String TEXT_4 = " < ";
  protected final String TEXT_5 = "; i_";
  protected final String TEXT_6 = "++) {" + NL + "       tasks_";
  protected final String TEXT_7 = ".get(i_";
  protected final String TEXT_8 = ").makeFinished();" + NL + "       if (tasks_";
  protected final String TEXT_9 = ").getMap().get(\"HAS_ERROR\") != null) {" + NL + "       \t\tforceShutdown_";
  protected final String TEXT_10 = " = true;" + NL + "       \t\tthrow (Exception)tasks_";
  protected final String TEXT_11 = ").getMap().get(\"HAS_ERROR\");" + NL + "       }" + NL + "       if (tasks_";
  protected final String TEXT_12 = ").getMap().get(\"THREADS_HAVE_ERROR\") != null) {" + NL + "       \t\tforceShutdown_";
  protected final String TEXT_13 = " = true;" + NL + "       \t\tglobalMap.put(\"FORCE_SHUTDOWN\",Boolean.TRUE);" + NL + "       \t\tthrow (Exception)tasks_";
  protected final String TEXT_14 = ").getMap().get(\"THREADS_HAVE_ERROR\");" + NL + "       }" + NL + "    }" + NL + "    " + NL + "    for (int i_";
  protected final String TEXT_15 = " < es_";
  protected final String TEXT_16 = ".size(); i_";
  protected final String TEXT_17 = "++) {" + NL + "    \ttry {" + NL + "       \t\tObject tmp_";
  protected final String TEXT_18 = " = es_";
  protected final String TEXT_19 = ".take().get();//don't need it for anything, hard return null. TODO consider move call get()." + NL + "       \t} catch (Exception ex_";
  protected final String TEXT_20 = ") {" + NL + "\t\t\tif(ex_";
  protected final String TEXT_21 = ".getClass()!=java.util.concurrent.CancellationException.class) {" + NL + "\t\t\t\tThrowable e_";
  protected final String TEXT_22 = " = ex_";
  protected final String TEXT_23 = ";" + NL + "\t\t\t\t// find the origin cause of the exception" + NL + "\t\t\t\tfor (int j_";
  protected final String TEXT_24 = " = 0; j_";
  protected final String TEXT_25 = " < 100 && e_";
  protected final String TEXT_26 = "!=null; j_";
  protected final String TEXT_27 = "++) {" + NL + "\t\t\t\t\tif (e_";
  protected final String TEXT_28 = ".getCause() == null) {" + NL + "\t\t\t\t\t\tbreak;" + NL + "\t\t\t\t\t} else {" + NL + "\t\t\t\t\t\te_";
  protected final String TEXT_29 = " = e_";
  protected final String TEXT_30 = ".getCause();" + NL + "\t\t\t\t\t}" + NL + "\t\t\t\t}" + NL + "\t\t\t\tif (e_";
  protected final String TEXT_31 = " instanceof Exception) {" + NL + "\t\t\t\t\tthrow (Exception)e_";
  protected final String TEXT_32 = ";" + NL + "\t\t\t\t} else {" + NL + "\t\t\t\t\tthrow ex_";
  protected final String TEXT_33 = ";" + NL + "\t\t\t\t}" + NL + "\t\t\t}" + NL + "\t\t}" + NL + "\t}" + NL + "    for (int i_";
  protected final String TEXT_34 = "++) {" + NL + "       \tif (tasks_";
  protected final String TEXT_35 = ").getMap().get(\"HAS_ERROR\");" + NL + "       \t}" + NL + "       \tif (tasks_";
  protected final String TEXT_36 = ").getMap().get(\"THREADS_HAVE_ERROR\");" + NL + "      \t}" + NL + "      \tjava.util.Map<String, Object> tmpMap = tasks_";
  protected final String TEXT_37 = ").getMap();" + NL + "       \tjava.util.Set<String> mapKeys_";
  protected final String TEXT_38 = " = tmpMap.keySet();" + NL + "       \tfor (String key_";
  protected final String TEXT_39 = " : mapKeys_";
  protected final String TEXT_40 = ") {" + NL + "       \t\t//should remove the key : \"THREAD_MAPS_";
  protected final String TEXT_41 = "_\"+jobName, and filter the key : \"BACKUP_GLOBAL_MAP_";
  protected final String TEXT_42 = "\" " + NL + "       \t\t//as it will make a infinite recursive when iterate the globalMap by user" + NL + "       \t\tif(key_";
  protected final String TEXT_43 = " == null || \"BACKUP_GLOBAL_MAP_";
  protected final String TEXT_44 = "\".equals(key_";
  protected final String TEXT_45 = ") " + NL + "       \t\t\t|| key_";
  protected final String TEXT_46 = ".startsWith(\"COMPLETED_\") " + NL + "       \t\t\t|| key_";
  protected final String TEXT_47 = ".startsWith(\"STARTED_\") " + NL + "       \t\t\t|| key_";
  protected final String TEXT_48 = ".startsWith(\"OUTQUEUE_\") " + NL + "       \t\t\t|| key_";
  protected final String TEXT_49 = ".startsWith(\"BEGIN_COUNT_\")" + NL + "       \t\t\t|| key_";
  protected final String TEXT_50 = ".endsWith(\"_SUBPROCESS_STATE\")) {" + NL + "       \t\t\tcontinue;" + NL + "       \t\t}" + NL + "       \t\t" + NL + "       \t\tif (key_";
  protected final String TEXT_51 = ".endsWith(\"NB_LINE\")) {" + NL + "       \t\t\tInteger mval_";
  protected final String TEXT_52 = " = (Integer)globalMap.get(key_";
  protected final String TEXT_53 = ");" + NL + "       \t\t\tInteger val_";
  protected final String TEXT_54 = " = (Integer)tmpMap.get(key_";
  protected final String TEXT_55 = ");" + NL + "       \t\t\tif(mval_";
  protected final String TEXT_56 = "!=null && val_";
  protected final String TEXT_57 = "!=null) {" + NL + "       \t\t\t\tglobalMap.put(key_";
  protected final String TEXT_58 = ",val_";
  protected final String TEXT_59 = "+mval_";
  protected final String TEXT_60 = ");" + NL + "       \t\t\t}" + NL + "       \t\t} else {" + NL + "       \t\t\tglobalMap.put(key_";
  protected final String TEXT_61 = ",tmpMap.get(key_";
  protected final String TEXT_62 = "));" + NL + "       \t\t}" + NL + "       \t}" + NL + "       \t" + NL + "       \tglobalMap.remove(\"THREAD_MAPS_";
  protected final String TEXT_63 = "_\"+jobName);" + NL + "    }" + NL + "    if (forceShutdown_";
  protected final String TEXT_64 = ") {" + NL + "\t    for (java.util.concurrent.Future<Object> f : futures_";
  protected final String TEXT_65 = ") {" + NL + "\t    \tf.cancel(true);" + NL + "\t    }" + NL + "\t    rootEs_";
  protected final String TEXT_66 = ".shutdownNow();" + NL + "    }else{" + NL + "    \trootEs_";
  protected final String TEXT_67 = ".shutdown();" + NL + "    }" + NL + "\tresourceMap.put(\"finish_";
  protected final String TEXT_68 = "\", true); ";
  protected final String TEXT_69 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
    CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
    INode node = (INode)codeGenArgument.getArgument();
    String cid = node.getUniqueName();	
    String numPartitions = ElementParameterParser.getValue(node, "__NUM_PARTITIONS__");
    String destinationColl = null;
	int recollTaskCount = 0;
    List<? extends INode> listRecoll= node.getProcess().getNodesOfType("tRecollector");
	if (listRecoll!=null && listRecoll.size() > 0 ) {
		recollTaskCount = listRecoll.size();
	}
   	boolean startRecollector = false;
    List<String> recs = new ArrayList<String>();
    List<? extends IConnection> startsConns = node.getOutgoingConnections(EConnectionType.STARTS);
    for (int i = 0; i < startsConns.size(); i++) {
    	IConnection conn = startsConns.get(i);
    	INode target = conn.getTarget();
    	if ("tCollector".equals(target.getComponent().getOriginalName()) && destinationColl == null) {
    		destinationColl = target.getUniqueName();
    	} else if ("tRecollector".equals(target.getComponent().getOriginalName())) {
    		startRecollector = true;
    		recs.add(target.getUniqueName());
    	}
    }
    boolean isLog4jEnabled = ("true").equals(ElementParameterParser.getValue(node.getProcess(), "__LOG4J_ACTIVATE__"));

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(numPartitions);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_66);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_68);
    stringBuffer.append(TEXT_69);
    return stringBuffer.toString();
  }
}
